# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
## Examples:
##   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

    
    Post.create( title3:"일본", img3: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/900px-Flag_of_Japan.svg.png")
    Post.create( title3:"중국", img3: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/900px-Flag_of_the_People%27s_Republic_of_China.svg.png")
    Post.create( title3:"필리핀", img3: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/900px-Flag_of_the_Philippines.svg.png")
    Post.create( title3:"베트남", img3: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/900px-Flag_of_Vietnam.svg.png")
    Post.create( title3:"인도", img3: "http://www.icons.or.kr/attach/board/migration/icons/cooper371/1243489097.02.jpg")
    Post.create( title3:"대만", img3: "http://cdnweb01.wikitree.co.kr/webdata/editor/201511/24/img_20151124142442_ed30474f.png")
    Post.create( title3:"홍콩", img3: "https://image-proxy.namuwikiusercontent.com/r/http%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F5%2F5b%2FFlag_of_Hong_Kong.svg%2F200px-Flag_of_Hong_Kong.svg.png")
    Post.create( title3:"태국", img3: "https://image-proxy.namuwikiusercontent.com/r/http%3A%2F%2Fwww.worldstatesmen.org%2Fth.gif")
    Post.create( title3:"싱가폴", img3: "https://image-proxy.namuwikiusercontent.com/r/http%3A%2F%2Fwww.worldstatesmen.org%2Fsg.gif")
    Post.create( title3:"호주", img3: "https://image-proxy.namuwikiusercontent.com/r/http%3A%2F%2Fwww.worldstatesmen.org%2Fau.gif")
    
    America.create( title2:"미국", img2: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/1024px-Flag_of_the_United_States.svg.png")
    America.create( title2:"캐나다", img2: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/225px-Flag_of_Canada.svg.png")
    America.create( title2:"멕시코", img2: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/225px-Flag_of_Mexico.svg.png")
    America.create( title2:"페루", img2: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/225px-Flag_of_Peru.svg.png")
    America.create( title2:"아르헨티나", img2: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/225px-Flag_of_Argentina.svg.png")
    America.create( title2:"브라질", img2: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/225px-Flag_of_Brazil.svg.png")
    
    Europe.create( title1:"프랑스", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/225px-Flag_of_France.svg.png")
    Europe.create( title1:"영국", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/225px-Flag_of_the_United_Kingdom.svg.png")
    Europe.create( title1:"독일", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/225px-Flag_of_Germany.svg.png")
    Europe.create( title1:"폴란드", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/225px-Flag_of_Poland.svg.png")
    Europe.create( title1:"이탈리아", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/225px-Flag_of_Italy.svg.png")
    Europe.create( title1:"스위스", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/225px-Flag_of_Switzerland_%28Pantone%29.svg.png")
    Europe.create( title1:"스페인", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/225px-Flag_of_Spain.svg.png")
    Europe.create( title1:"체코", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/225px-Flag_of_the_Czech_Republic.svg.png")
    Europe.create( title1:"오스트리아", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/225px-Flag_of_Austria.svg.png")
    Europe.create( title1:"포르투갈", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/225px-Flag_of_Portugal.svg.png")
    Europe.create( title1:"터키", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/225px-Flag_of_Turkey.svg.png")
    Europe.create( title1:"러시아", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/225px-Flag_of_Russia.svg.png")
    Europe.create( title1:"네덜란드", img1: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/225px-Flag_of_the_Netherlands.svg.png")
    Africa.create( title:"이집트", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/225px-Flag_of_Egypt.svg.png")
    Africa.create( title:"남아공", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/225px-Flag_of_South_Africa.svg.png")
